// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // AfriLove World Firebase project (afrilove-world).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJINNe9iwb6_GYsLi6V_XfTUxgaywuCRE',
    appId: '1:949332317190:android:f729fb77c3fe3f8279df87',
    messagingSenderId: '949332317190',
    projectId: 'afrilove-world',
    storageBucket: 'afrilove-world.firebasestorage.app',
  );

  // TODO(iOS): still points to the previous project. To enable Firebase on
  // iOS, register an iOS app (bundle id com.afriloveworld.app) in the
  // afrilove-world project and replace the values below (or run
  // `flutterfire configure`).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-YvGGlTSZh1IcX9OraGn_csnPfpRlM4',
    appId: '1:319710447950:ios:33256ef735bf5158a2f61f',
    messagingSenderId: '319710447950',
    projectId: 'redbus-3ec46',
    storageBucket: 'redbus-3ec46.appspot.com',
    androidClientId: '319710447950-2ltd456epi1h5g6igoaqsiv2efj4cepg.apps.googleusercontent.com',
    iosClientId: '319710447950-7o1oapai6u596493ehbee68t5a4l5ijk.apps.googleusercontent.com',
    iosBundleId: 'com.afriloveworld.app',
  );
}
